### ISSUE TITLE
Pre-trained Models

### ISSUE THREAD

**Issue by rzamarefat** [rohitkuk/Cartoonify#1]
Hi, thanks for sharing this repo. Is there any chance to have access to the pre-trained checkpoint?

**Comment by rohitkuk** [comment]
Hi @rzamarefat 

I don't know if it is still relevant but please find the preTrained weights for the Generator.

https://models-checkpoints-to-share.s3.ap-south-1.amazonaws.com/Cartoonify_Generator.pt
